### PR TITLE
searching for composers completed: /api/searchComposers

### PR DESCRIPTION
**Pull request by apollomoon-ucf**
https://app.swaggerhub.com/apis/apollomoon-ucf/Composition_Today_API/1.0.0?loggedInWithGitHub=true#/User%20Endpoints/searchComposers

### CODE REVIEW

**Review by NeoUCF — CHANGES_REQUESTED** [review]
As always, great work!
I think there is a typo on firstName on line 58.

**Review by FedericoBaron — APPROVED** [review]
awesome job Brian!

**Comment by apollomoon-ucf** [comment]
Thanks for the feedback! :)

**Review by NeoUCF — APPROVED** [review]
Yay!!! It works like a charm.
Awesome job

**Pull request merged**
